/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : Status,
  'created' : bigint,
  'checkIn' : string,
  'owner' : Principal,
  'guestCount' : bigint,
  'hotelId' : bigint,
  'guestName' : string,
  'guestEmail' : string,
  'checkOut' : string,
  'phone' : string,
}
export interface Hotel {
  'id' : bigint,
  'starRating' : bigint,
  'city' : string,
  'pricePerNight' : bigint,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'imageIndex' : bigint,
}
export interface HotelQueryParams {
  'city' : [] | [string],
  'amenities' : [] | [Array<string>],
  'maxPrice' : [] | [bigint],
  'minPrice' : [] | [bigint],
}
export interface PropertyListing {
  'id' : bigint,
  'ownerEmail' : string,
  'status' : PropertyListingStatus,
  'hotelName' : string,
  'ownerName' : string,
  'city' : string,
  'pricePerNight' : bigint,
  'subscriptionPlan' : string,
  'ownerPhone' : string,
  'submittedAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'roomType' : string,
}
export type PropertyListingStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'PendingApproval' : null };
export type Status = { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePropertyListing' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, bigint],
    bigint
  >,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHotel' : ActorMethod<[bigint], Hotel>,
  'getMyPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectPropertyListing' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchHotels' : ActorMethod<[HotelQueryParams], Array<Hotel>>,
  'submitPropertyListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      string,
      string,
      bigint,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];