/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'created' : IDL.Int,
  'checkIn' : IDL.Text,
  'owner' : IDL.Principal,
  'guestCount' : IDL.Nat,
  'hotelId' : IDL.Nat,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'checkOut' : IDL.Text,
  'phone' : IDL.Text,
});
export const BlockedDate = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'hotelId' : IDL.Nat,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const HotelApprovalStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Hotel = IDL.Record({
  'id' : IDL.Nat,
  'starRating' : IDL.Nat,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'approvalStatus' : HotelApprovalStatus,
  'address' : IDL.Text,
  'imageIndex' : IDL.Nat,
});
export const PropertyListingStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'PendingApproval' : IDL.Null,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'ownerEmail' : IDL.Text,
  'status' : PropertyListingStatus,
  'hotelName' : IDL.Text,
  'ownerName' : IDL.Text,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Int,
  'subscriptionPlan' : IDL.Text,
  'ownerPhone' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'roomType' : IDL.Text,
});
export const RoomInventory = IDL.Record({
  'availableRooms' : IDL.Nat,
  'hotelId' : IDL.Nat,
  'roomType' : IDL.Text,
  'totalRooms' : IDL.Nat,
});
export const HotelQueryParams = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
  'maxPrice' : IDL.Opt(IDL.Int),
  'minPrice' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveHotel' : IDL.Func([IDL.Nat], [], []),
  'approvePropertyListing' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignHotelOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'blockDate' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBlockedDates' : IDL.Func([], [IDL.Vec(BlockedDate)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotel' : IDL.Func([IDL.Nat], [Hotel], ['query']),
  'getHotelsForAdmin' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyPropertyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getOwnerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getOwnerHotel' : IDL.Func([], [Hotel], ['query']),
  'getOwnerRoomInventory' : IDL.Func([], [RoomInventory], ['query']),
  'getPropertyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectHotel' : IDL.Func([IDL.Nat], [], []),
  'rejectPropertyListing' : IDL.Func([IDL.Nat], [], []),
  'revokeHotelOwner' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchHotels' : IDL.Func([HotelQueryParams], [IDL.Vec(Hotel)], ['query']),
  'submitPropertyListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'unblockDate' : IDL.Func([IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateRoomInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'created' : IDL.Int,
    'checkIn' : IDL.Text,
    'owner' : IDL.Principal,
    'guestCount' : IDL.Nat,
    'hotelId' : IDL.Nat,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'checkOut' : IDL.Text,
    'phone' : IDL.Text,
  });
  const BlockedDate = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'hotelId' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const HotelApprovalStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Hotel = IDL.Record({
    'id' : IDL.Nat,
    'starRating' : IDL.Nat,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'approvalStatus' : HotelApprovalStatus,
    'address' : IDL.Text,
    'imageIndex' : IDL.Nat,
  });
  const PropertyListingStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'PendingApproval' : IDL.Null,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'ownerEmail' : IDL.Text,
    'status' : PropertyListingStatus,
    'hotelName' : IDL.Text,
    'ownerName' : IDL.Text,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Int,
    'subscriptionPlan' : IDL.Text,
    'ownerPhone' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'roomType' : IDL.Text,
  });
  const RoomInventory = IDL.Record({
    'availableRooms' : IDL.Nat,
    'hotelId' : IDL.Nat,
    'roomType' : IDL.Text,
    'totalRooms' : IDL.Nat,
  });
  const HotelQueryParams = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
    'maxPrice' : IDL.Opt(IDL.Int),
    'minPrice' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveHotel' : IDL.Func([IDL.Nat], [], []),
    'approvePropertyListing' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignHotelOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'blockDate' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBlockedDates' : IDL.Func([], [IDL.Vec(BlockedDate)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotel' : IDL.Func([IDL.Nat], [Hotel], ['query']),
    'getHotelsForAdmin' : IDL.Func([], [IDL.Vec(Hotel)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyPropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getOwnerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getOwnerHotel' : IDL.Func([], [Hotel], ['query']),
    'getOwnerRoomInventory' : IDL.Func([], [RoomInventory], ['query']),
    'getPropertyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectHotel' : IDL.Func([IDL.Nat], [], []),
    'rejectPropertyListing' : IDL.Func([IDL.Nat], [], []),
    'revokeHotelOwner' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchHotels' : IDL.Func([HotelQueryParams], [IDL.Vec(Hotel)], ['query']),
    'submitPropertyListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'unblockDate' : IDL.Func([IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateRoomInventory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };