/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'created' : IDL.Int,
  'checkIn' : IDL.Text,
  'owner' : IDL.Principal,
  'guestCount' : IDL.Nat,
  'hotelId' : IDL.Nat,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'checkOut' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Hotel = IDL.Record({
  'id' : IDL.Nat,
  'starRating' : IDL.Nat,
  'city' : IDL.Text,
  'pricePerNight' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'imageIndex' : IDL.Nat,
});
export const HotelQueryParams = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
  'maxPrice' : IDL.Opt(IDL.Int),
  'minPrice' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHotel' : IDL.Func([IDL.Nat], [Hotel], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchHotels' : IDL.Func([HotelQueryParams], [IDL.Vec(Hotel)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'created' : IDL.Int,
    'checkIn' : IDL.Text,
    'owner' : IDL.Principal,
    'guestCount' : IDL.Nat,
    'hotelId' : IDL.Nat,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'checkOut' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Hotel = IDL.Record({
    'id' : IDL.Nat,
    'starRating' : IDL.Nat,
    'city' : IDL.Text,
    'pricePerNight' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'imageIndex' : IDL.Nat,
  });
  const HotelQueryParams = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'amenities' : IDL.Opt(IDL.Vec(IDL.Text)),
    'maxPrice' : IDL.Opt(IDL.Int),
    'minPrice' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHotel' : IDL.Func([IDL.Nat], [Hotel], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchHotels' : IDL.Func([HotelQueryParams], [IDL.Vec(Hotel)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };