/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CustomerProfile {
    name: string;
    email: string;
    memberSince: bigint;
    passwordHash: string;
    mobile: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PropertyListing {
    id: bigint;
    ownerEmail: string;
    status: PropertyListingStatus;
    hotelName: string;
    ownerName: string;
    imageUrls: Array<string>;
    city: string;
    pricePerNight: bigint;
    subscriptionPlan: string;
    ownerPhone: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    amenities: Array<string>;
    address: string;
    kycDocumentUrl: string;
    roomType: string;
    rules: string;
}
export interface HotelQueryParams {
    city?: string;
    amenities?: Array<string>;
    maxPrice?: bigint;
    minPrice?: bigint;
}
export interface Hotel {
    id: bigint;
    ownerEmail: string;
    starRating: bigint;
    imageUrls: Array<string>;
    city: string;
    ownerPrincipal: string;
    pricePerNight: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    approvalStatus: HotelApprovalStatus;
    address: string;
    imageIndex: bigint;
    rules: string;
}
export interface RoomInventory {
    availableRooms: bigint;
    hotelId: bigint;
    roomType: string;
    totalRooms: bigint;
}
export interface Booking {
    id: bigint;
    status: Status;
    created: bigint;
    checkIn: string;
    owner: Principal;
    guestCount: bigint;
    hotelId: bigint;
    guestName: string;
    guestEmail: string;
    checkOut: string;
    phone: string;
}
export interface BlockedDate {
    id: bigint;
    date: string;
    hotelId: bigint;
    reason: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum HotelApprovalStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum PropertyListingStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    PendingApproval = "PendingApproval"
}
export enum Status {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHotelAdmin(name: string, city: string, description: string, starRating: bigint, pricePerNight: bigint, amenities: Array<string>, address: string, imageIndex: bigint, imageUrls: Array<string>, rules: string): Promise<bigint>;
    approveHotel(id: bigint): Promise<void>;
    approvePropertyListing(listingId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignHotelOwner(user: Principal, hotelId: bigint): Promise<void>;
    blockDate(date: string, reason: string): Promise<bigint>;
    cancelBooking(id: bigint): Promise<void>;
    changeCustomerPassword(newPasswordHash: string): Promise<void>;
    createBooking(hotelId: bigint, guestName: string, guestEmail: string, phone: string, checkIn: string, checkOut: string, guestCount: bigint): Promise<bigint>;
    generateAdminOtp(): Promise<string>;
    getAdminLockStatus(): Promise<boolean>;
    getAllBookings(): Promise<Array<Booking>>;
    getBlockedDates(): Promise<Array<BlockedDate>>;
    getBooking(id: bigint): Promise<Booking>;
    getBookingsByEmail(email: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerProfile(): Promise<CustomerProfile | null>;
    getHotel(id: bigint): Promise<Hotel>;
    getHotelImageUrls(id: bigint): Promise<Array<string>>;
    getHotelsForAdmin(): Promise<Array<Hotel>>;
    getKycDocumentUrl(listingId: bigint): Promise<string>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyPropertyListings(): Promise<Array<PropertyListing>>;
    getOwnerBookings(): Promise<Array<Booking>>;
    getOwnerHotel(): Promise<Hotel>;
    getOwnerHotelByEmail(email: string): Promise<Hotel>;
    getOwnerRoomInventory(): Promise<RoomInventory>;
    getPropertyListings(): Promise<Array<PropertyListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerHotelOwner(): Promise<boolean>;
    loginCustomer(email: string, passwordHash: string): Promise<boolean>;
    registerCustomer(name: string, email: string, mobile: string, passwordHash: string): Promise<void>;
    rejectHotel(id: bigint): Promise<void>;
    rejectPropertyListing(listingId: bigint): Promise<void>;
    revokeHotelOwner(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchHotels(queryParams: HotelQueryParams): Promise<Array<Hotel>>;
    submitPropertyListing(ownerName: string, ownerPhone: string, ownerEmail: string, hotelName: string, city: string, address: string, pricePerNight: bigint, roomType: string, amenities: Array<string>, description: string, subscriptionPlan: string, submittedAt: bigint, imageUrls: Array<string>, kycDocumentUrl: string, rules: string): Promise<bigint>;
    suspendHotel(id: bigint): Promise<void>;
    unblockDate(blockedDateId: bigint): Promise<void>;
    unlockAdminAccount(): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: Status): Promise<void>;
    updateCustomerProfile(name: string, email: string, mobile: string): Promise<void>;
    updateHotelRules(rules: string): Promise<void>;
    updateRoomInventory(totalRooms: bigint, availableRooms: bigint): Promise<void>;
    verifyAdminOtp(code: string): Promise<boolean>;
}
import type { Booking as _Booking, CustomerProfile as _CustomerProfile, Hotel as _Hotel, HotelApprovalStatus as _HotelApprovalStatus, HotelQueryParams as _HotelQueryParams, PropertyListing as _PropertyListing, PropertyListingStatus as _PropertyListingStatus, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHotelAdmin(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: Array<string>, arg6: string, arg7: bigint, arg8: Array<string>, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHotelAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHotelAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async approveHotel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveHotel(arg0);
            return result;
        }
    }
    async approvePropertyListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePropertyListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePropertyListing(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignHotelOwner(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignHotelOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignHotelOwner(arg0, arg1);
            return result;
        }
    }
    async blockDate(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.blockDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockDate(arg0, arg1);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async changeCustomerPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeCustomerPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeCustomerPassword(arg0);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async generateAdminOtp(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAdminOtp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAdminOtp();
            return result;
        }
    }
    async getAdminLockStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminLockStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminLockStatus();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedDates(): Promise<Array<BlockedDate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedDates();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByEmail(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEmail(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEmail(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotel(arg0: bigint): Promise<Hotel> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotel(arg0);
                return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotel(arg0);
            return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHotelImageUrls(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelImageUrls(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelImageUrls(arg0);
            return result;
        }
    }
    async getHotelsForAdmin(): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotelsForAdmin();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotelsForAdmin();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKycDocumentUrl(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getKycDocumentUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKycDocumentUrl(arg0);
            return result;
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPropertyListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPropertyListings();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPropertyListings();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerHotel(): Promise<Hotel> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerHotel();
                return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerHotel();
            return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerHotelByEmail(arg0: string): Promise<Hotel> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerHotelByEmail(arg0);
                return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerHotelByEmail(arg0);
            return from_candid_Hotel_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerRoomInventory(): Promise<RoomInventory> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerRoomInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerRoomInventory();
            return result;
        }
    }
    async getPropertyListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyListings();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyListings();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerHotelOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerHotelOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerHotelOwner();
            return result;
        }
    }
    async loginCustomer(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCustomer(arg0, arg1);
            return result;
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectHotel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectHotel(arg0);
            return result;
        }
    }
    async rejectPropertyListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPropertyListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPropertyListing(arg0);
            return result;
        }
    }
    async revokeHotelOwner(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeHotelOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeHotelOwner(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchHotels(arg0: HotelQueryParams): Promise<Array<Hotel>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchHotels(to_candid_HotelQueryParams_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchHotels(to_candid_HotelQueryParams_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPropertyListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: Array<string>, arg9: string, arg10: string, arg11: bigint, arg12: Array<string>, arg13: string, arg14: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPropertyListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPropertyListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            return result;
        }
    }
    async suspendHotel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendHotel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendHotel(arg0);
            return result;
        }
    }
    async unblockDate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockDate(arg0);
            return result;
        }
    }
    async unlockAdminAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAdminAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAdminAccount();
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomerProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateHotelRules(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHotelRules(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHotelRules(arg0);
            return result;
        }
    }
    async updateRoomInventory(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomInventory(arg0, arg1);
            return result;
        }
    }
    async verifyAdminOtp(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminOtp(arg0);
            return result;
        }
    }
}
function from_candid_Booking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_HotelApprovalStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HotelApprovalStatus): HotelApprovalStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Hotel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hotel): Hotel {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListingStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListingStatus): PropertyListingStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListing_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    created: bigint;
    checkIn: string;
    owner: Principal;
    guestCount: bigint;
    hotelId: bigint;
    guestName: string;
    guestEmail: string;
    checkOut: string;
    phone: string;
}): {
    id: bigint;
    status: Status;
    created: bigint;
    checkIn: string;
    owner: Principal;
    guestCount: bigint;
    hotelId: bigint;
    guestName: string;
    guestEmail: string;
    checkOut: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        created: value.created,
        checkIn: value.checkIn,
        owner: value.owner,
        guestCount: value.guestCount,
        hotelId: value.hotelId,
        guestName: value.guestName,
        guestEmail: value.guestEmail,
        checkOut: value.checkOut,
        phone: value.phone
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownerEmail: string;
    starRating: bigint;
    imageUrls: Array<string>;
    city: string;
    ownerPrincipal: string;
    pricePerNight: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    approvalStatus: _HotelApprovalStatus;
    address: string;
    imageIndex: bigint;
    rules: string;
}): {
    id: bigint;
    ownerEmail: string;
    starRating: bigint;
    imageUrls: Array<string>;
    city: string;
    ownerPrincipal: string;
    pricePerNight: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    approvalStatus: HotelApprovalStatus;
    address: string;
    imageIndex: bigint;
    rules: string;
} {
    return {
        id: value.id,
        ownerEmail: value.ownerEmail,
        starRating: value.starRating,
        imageUrls: value.imageUrls,
        city: value.city,
        ownerPrincipal: value.ownerPrincipal,
        pricePerNight: value.pricePerNight,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        approvalStatus: from_candid_HotelApprovalStatus_n21(_uploadFile, _downloadFile, value.approvalStatus),
        address: value.address,
        imageIndex: value.imageIndex,
        rules: value.rules
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownerEmail: string;
    status: _PropertyListingStatus;
    hotelName: string;
    ownerName: string;
    imageUrls: Array<string>;
    city: string;
    pricePerNight: bigint;
    subscriptionPlan: string;
    ownerPhone: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    amenities: Array<string>;
    address: string;
    kycDocumentUrl: string;
    roomType: string;
    rules: string;
}): {
    id: bigint;
    ownerEmail: string;
    status: PropertyListingStatus;
    hotelName: string;
    ownerName: string;
    imageUrls: Array<string>;
    city: string;
    pricePerNight: bigint;
    subscriptionPlan: string;
    ownerPhone: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    amenities: Array<string>;
    address: string;
    kycDocumentUrl: string;
    roomType: string;
    rules: string;
} {
    return {
        id: value.id,
        ownerEmail: value.ownerEmail,
        status: from_candid_PropertyListingStatus_n27(_uploadFile, _downloadFile, value.status),
        hotelName: value.hotelName,
        ownerName: value.ownerName,
        imageUrls: value.imageUrls,
        city: value.city,
        pricePerNight: value.pricePerNight,
        subscriptionPlan: value.subscriptionPlan,
        ownerPhone: value.ownerPhone,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        amenities: value.amenities,
        address: value.address,
        kycDocumentUrl: value.kycDocumentUrl,
        roomType: value.roomType,
        rules: value.rules
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): Status {
    return "Confirmed" in value ? Status.Confirmed : "Cancelled" in value ? Status.Cancelled : "Pending" in value ? Status.Pending : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): HotelApprovalStatus {
    return "Approved" in value ? HotelApprovalStatus.Approved : "Rejected" in value ? HotelApprovalStatus.Rejected : "Pending" in value ? HotelApprovalStatus.Pending : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    PendingApproval: null;
}): PropertyListingStatus {
    return "Approved" in value ? PropertyListingStatus.Approved : "Rejected" in value ? PropertyListingStatus.Rejected : "PendingApproval" in value ? PropertyListingStatus.PendingApproval : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hotel>): Array<Hotel> {
    return value.map((x)=>from_candid_Hotel_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n25(_uploadFile, _downloadFile, x));
}
function to_candid_HotelQueryParams_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HotelQueryParams): _HotelQueryParams {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    amenities?: Array<string>;
    maxPrice?: bigint;
    minPrice?: bigint;
}): {
    city: [] | [string];
    amenities: [] | [Array<string>];
    maxPrice: [] | [bigint];
    minPrice: [] | [bigint];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        amenities: value.amenities ? candid_some(value.amenities) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == Status.Confirmed ? {
        Confirmed: null
    } : value == Status.Cancelled ? {
        Cancelled: null
    } : value == Status.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
